name: Build Android APK

on:
  push:
    branches: [ "main", "master" ] # Push karne par automatic chalega
  workflow_dispatch: # GitHub Actions tab se manual run karne ke liye bhi

jobs:
  build:
    name: Build Native APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper & Build APK
        working-directory: ./Loki-Android
        run: |
          # Agar gradlew file nahi hai, to global gradle use karke generate kar lenge
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: Loki-X-Prime-App
          path: Loki-Android/app/build/outputs/apk/debug/app-debug.apk
